---
- hosts: all
  gather_facts: true 
  connection: local

  tasks:
   - name: Configure VRF
     when: tenant_configs
     ios_config:
       commands: ip vrf {{ item.vrf }}
       provider: "{{ cli }}"
     with_items: "{{tenant_configs}}"

   - name: Configure inside interface
     when: tenant_configs
     ios_config:
       commands:
         - encapsulation dot1Q {{ item.vlan_id }}
         - ip vrf forwarding {{ item.vrf }}
         - ip address {{ item.gateway }} 255.255.255.0
         - ip nat inside
       parents: interface {{ ansible_env.INSIDE_INTERFACE }}.{{ item.vlan_id }}
       provider: "{{ cli }}"
     with_items: "{{tenant_configs}}"

   - name: Configure Dynamic PAT
     when: tenant_configs
     ios_config:
       commands: ip nat inside source list NAT interface {{ ansible_env.OUTSIDE_INTERFACE }} vrf {{ item.vrf }} overload
       provider: "{{ cli }}"
     with_items: "{{tenant_configs}}"

   - name: Configure static NAT
     when: floating_ip_configs
     ios_config:
       commands: ip nat inside source static {{ item.local_ip }} {{ item.global_ip }} vrf {{ item.vrf }}
       provider: "{{ cli }}"
     with_items: "{{floating_ip_configs}}"

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_env.IOS_USER }}"
      password: "{{ ansible_env.IOS_PASS }}"
      auth_pass: "{{ ansible_env.IOS_ENABLE_PASS }}"
      authorize: true
